template: |
  ## Changelog

  $CHANGES

changelog-filters:
  # Include all changes
  include-labels: []
  # Exclude changes with these labels
  exclude-labels:
    - skip-changelog

version-resolvers:
  # Use the existing latest tag
  tag: latest

# Publish the release automatically
update-releases: true

# Close the draft release
close-milestone: true