CREATE TABLE DONATION(
	DONATION_ID INT AUTO_INCREMENT PRIMARY KEY,
	DONER_NAME VARCHAR(50),
	DONATION_DESCRIPTION VARCHAR(100) NOT NULL,
	DONATION_AMOUNT DOUBLE NOT NULL,
	DONATION_DATE DATE NOT NULL,
	ALUMNI_ID INT  NULL,
	CREATE_TS DATETIME,
	CREATE_USER VARCHAR(50),
	UPDATE_TS DATETIME,
	UDPATE_USER VARCHAR(50),
	CONSTRAINT DONATION_FK FOREIGN KEY (ALUMNI_ID) REFERENCES ALUMNI(ALUMNI_ID)
);