USE alumni;

CREATE TABLE ALUMNI (
	ALUMNI_ID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL,
	ROLE_ID INT NOT NULL,
	FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR(45) NOT NULL,
	CONSTRAINT ALUMNI_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)
);