CREATE TABLE TRANSACTION (
	TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
	TRANSACTION_DATE CHAR(10) NOT NULL,
	NAME_ON_CARD CHAR(20) NOT NULL,
	CREDIT_CARD_NUMBER INT NOT NULL,
	EXPIRY_DATE CHAR(10) NOT NULL,
	ALUMNI_ID INT NULL,
	EVENT_ID INT  NULL,
	DONATION_ID INT  NULL,
	CREATE_TS DATETIME NOT NULL,
	CREATE_USER CHAR(20) NOT NULL,
	UPDATE_TS DATETIME NULL,
	CONSTRAINT TRANSACTION_FK FOREIGN KEY(ALUMNI_ID) REFERENCES ALUMNI (ALUMNI_ID),
	CONSTRAINT TRANSACTION_FK1 FOREIGN KEY(EVENT_ID) REFERENCES EVENTS (EVENT_ID)
);