USE alumni;
CREATE TABLE EVENT_TRANSACTION (
	TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
	ALUMNI_ID INT NULL,
    EVENT_ID INT  NULL,
	TRANSACTION_DATE DATE NOT NULL,
	NAME_ON_CARD CHAR(20) NOT NULL,
	CARD_NUMBER  BIGINT NOT NULL,
	EXPIRY_DATE CHAR(10) NOT NULL,
	CARD_TYPE VARCHAR(50),
	CREATE_TS DATETIME NOT NULL,
	CREATE_USER CHAR(20) NOT NULL,
	UPDATE_TS DATETIME NULL,
	UPDATE_USER CHAR(20),
	CONSTRAINT TRANSACTION_FK FOREIGN KEY(ALUMNI_ID) REFERENCES ALUMNI (ALUMNI_ID),
	CONSTRAINT TRANSACTION_FK1 FOREIGN KEY(EVENT_ID) REFERENCES EVENTS (EVENT_ID)
);