USE alumni;
CREATE TABLE EVENTS(
	EVENT_ID INT AUTO_INCREMENT PRIMARY KEY,
	EVENT_NAME VARCHAR(50) NOT NULL,
	EVENT_DESCRIPTION VARCHAR(50) NOT NULL,
	START_DATE_TIME DATETIME NOT NULL,
	EVENT_ORGANISER VARCHAR(50) NOT NULL,
	EVENT_LOCATION VARCHAR(50) NOT NULL,
	TICKET_PRICE INT NOT NULL,
	CREATE_TS DATETIME NOT NULL,
	CREATE_USER VARCHAR(50) NOT NULL,
	UPDATE_TS DATETIME,
	UPDATE_USER VARCHAR(20)
);