CREATE TABLE ALUMNI (
	ALUMNI_ID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL,
	ROLE_ID INT NOT NULL,
	FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR(45) NOT NULL,
	ADDRESS VARCHAR(100),
	INSTITUTION_NAME VARCHAR(45) NOT NULL,
	GRADUATION_YEAR DATE NOT NULL,
	GRADUATION_MONTH DATE,
	SCHOOLYEAR VARCHAR(45),
	INTERESTS VARCHAR(100),
	CREATE_TS DATETIME,
	CREATE_USER VARCHAR(50),
	UPDATE_TS DATETIME,
	UDPATE_USER VARCHAR(50),
	CONSTRAINT ALUMNI_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)
);