USE alumni;
CREATE TABLE `TRANSACTION` (
  `TRANSACTION_ID` int NOT NULL AUTO_INCREMENT,
  `TRANSACTION_TYPE` varchar(20) NOT NULL,
  `ALUMNI_ID` int DEFAULT NULL,
  `EVENT_ID` int DEFAULT NULL,
  `TRANSACTION_DATE` date NOT NULL,
  `NAME_ON_CARD` char(20) NOT NULL,
  `CARD_NUMBER` bigint NOT NULL,
  `EXPIRY_DATE` char(10) NOT NULL,
  `CARD_TYPE` varchar(50) DEFAULT NULL,
  `AMOUNT` bigint NOT NULL,
  `CREATE_TS` datetime NOT NULL,
  `CREATE_USER` char(20) NOT NULL,
  `UPDATE_TS` datetime DEFAULT NULL,
  `UPDATE_USER` char(20) DEFAULT NULL,
  PRIMARY KEY (`TRANSACTION_ID`),
  KEY `TRANSACTION_FK` (`ALUMNI_ID`),
  KEY `TRANSACTION_FK1` (`EVENT_ID`),
  CONSTRAINT `TRANSACTION_FK` FOREIGN KEY (`ALUMNI_ID`) REFERENCES `alumni` (`ALUMNI_ID`),
  CONSTRAINT `TRANSACTION_FK1` FOREIGN KEY (`EVENT_ID`) REFERENCES `event` (`EVENT_ID`)
);
