USE alumni;
CREATE TABLE EVENT(
	EVENT_ID INT AUTO_INCREMENT PRIMARY KEY,
	EVENT_NAME VARCHAR(100) NOT NULL,
	EVENT_DESCRIPTION VARCHAR(1000) NOT NULL,
	START_DATE_TIME DATETIME NOT NULL,
	EVENT_LOCATION VARCHAR(1000) NOT NULL,
    	IMAGE VARCHAR(100) NOT NULL,
	TICKET_PRICE DOUBLE NOT NULL,
	CREATE_TS DATETIME default CURRENT_TIMESTAMP,
	CREATE_USER VARCHAR(50),
	UPDATE_TS DATETIME default CURRENT_TIMESTAMP,
	UPDATE_USER VARCHAR(50)
);
