USE alumni;

CREATE TABLE `ALUMNI` (
  `ALUMNI_ID` int NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `ROLE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ALUMNI_ID`)
) ;
