CREATE TABLE CONTENT(
	CONTENT_ID INT AUTO_INCREMENT PRIMARY KEY,
	CONTENT_NAME VARCHAR(100) NOT NULL,
	CONTENT_TYPE VARCHAR(45) NOT NULL,
	CONTENT_DESCRIPTION VARCHAR(500),
	CONTENT_PHOTO_URL VARCHAR(300),
	CONTENT_VIDEO_URL VARCHAR(300),
	ALUMNI_ID INT NOT NULL,
	CREATE_TS DATETIME,
	CREATE_USER VARCHAR(50),
	UPDATE_TS DATETIME,
	UDPATE_USER VARCHAR(50),
	CONSTRAINT CONTENT_FK FOREIGN KEY(ALUMNI_ID) REFERENCES ALUMNI(ALUMNI_ID)
);