USE alumni;
CREATE TABLE DONATION(
	DONATION_ID INT AUTO_INCREMENT PRIMARY KEY,
	DONATION_DESCRIPTION VARCHAR(100) NOT NULL,
	DONATION_AMOUNT DOUBLE NOT NULL,
	DONATION_DATE DATE NOT NULL,
	ALUMNI_ID INT  NULL,
	NAME_ON_CARD CHAR(20) NOT NULL,
    CREDIT_CARD_NUMBER INT NOT NULL,
    EXPIRY_DATE CHAR(10) NOT NULL,
    CARD_TYPE VARCHAR(50),
	CREATE_TS DATETIME NOT NULL,
	CREATE_USER VARCHAR(50) NOT NULL,
	UPDATE_TS DATETIME,
	UDPATE_USER VARCHAR(50),
	CONSTRAINT DONATION_FK FOREIGN KEY (ALUMNI_ID) REFERENCES ALUMNI(ALUMNI_ID)
);