USE alumni;
CREATE TABLE `EVENT` (
  `EVENT_ID` int NOT NULL AUTO_INCREMENT,
  `EVENT_NAME` varchar(50) NOT NULL,
  `EVENT_DESCRIPTION` varchar(50) NOT NULL,
  `START_DATE_TIME` datetime NOT NULL,
  `EVENT_LOCATION` varchar(50) NOT NULL,
  `IMAGE` varchar(100) NOT NULL,
  `TICKET_PRICE` int NOT NULL,
  `CREATE_TS` datetime NOT NULL,
  `CREATE_USER` varchar(50) NOT NULL,
  `UPDATE_TS` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`EVENT_ID`)
) ;