name: Release Drafter

on:
  release:
    types:
      - published

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check release notes file
        run: |
          if [ ! -f $RD_ARTIFACTS_DIR/release-changelog.md ]; then
            echo "Release notes file not found"
            exit 1
          fi
      - name: Add release notes to latest tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          tag_name=${latest_tag##*/}
          release_notes=$(cat $RD_ARTIFACTS_DIR/release-changelog.md)
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -X PATCH \
               -d "{\"body\": \"$release_notes\"}" \
               "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ github.event.release.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
