name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5.16.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/release-drafter.yml

      - name: Update Release Body
        uses: peter-evans/create-pull-request@v3.12.0
        with:
          commit-message: Update release body with release notes
          title: Update release body with release notes
          body: |
            ${{ steps.drafter.outputs.changelog }}
          branch: update-release-body
          base: ${{ github.ref }}
          author: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
