name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5.16.0
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Release Body
        uses: peter-evans/create-pull-request@v3.12.0
        with:
          commit-message: Update release body with release notes
          title: Update release body with release notes
          body: |
            ${{ steps.drafter.outputs.changelog }}
          branch: update-release-body
          base: ${{ github.ref }}
          author: "Ridhima Kohli <ridhimakohli2901@gmail.com>"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
